# Generated by Django 4.0.6 on 2022-09-30 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', related_query_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
