# Generated by Django 4.0.6 on 2022-09-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('director', '감독'), ('writer', '극본'), ('actor', '배우')], max_length=8)),
                ('cameo_type', models.CharField(blank=True, choices=[('special', '특별출연'), ('writer', '극본'), ('friend', '우정출연')], max_length=7)),
                ('role_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('kmdb_id', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('synopsys', models.TextField(blank=True)),
                ('film_rating', models.CharField(blank=True, choices=[('ALL', '전체관람가'), ('12', '12세이상관람가'), ('15', '15세이상관람가'), ('18', '청소년관람불가'), ('R18', '제한상영가')], max_length=3)),
                ('countries', models.ManyToManyField(blank=True, to='movies.country')),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('kmdb_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('biography', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(choices=[('youtube', 'YouTube')], max_length=7)),
                ('external_id', models.CharField(max_length=11)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Still',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_main', models.BooleanField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='staffs',
            field=models.ManyToManyField(through='movies.Credit', to='movies.people'),
        ),
        migrations.AddField(
            model_name='credit',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='credit',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmography', to='movies.people'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('movie', 'title'), name='unique_title_in_movie'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('movie', 'site', 'external_id'), name='unique_video_in_movie'),
        ),
        migrations.AddConstraint(
            model_name='still',
            constraint=models.UniqueConstraint(fields=('movie', 'image_url'), name='unique_still_in_movie'),
        ),
        migrations.AddConstraint(
            model_name='poster',
            constraint=models.UniqueConstraint(fields=('movie', 'image_url'), name='unique_poster_in_movie'),
        ),
    ]
