# Generated by Django 4.0.6 on 2022-10-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='people',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='staffs',
            new_name='people',
        ),
    ]
